channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - conda-forge::python >=3.12
  - conda-forge::mamba >=1.5.8
  - conda-forge::lmod >= 8.7.25
  - conda-forge::pip >= 24.1.2
  - conda-forge::datrie >= 0.8.2 # dep for snakemake, workaround for https://github.com/astral-sh/uv/issues/7525
  - pip:
     - "."
